input_text_column: description
label_text_column: short_query
dataset: smartcat/Amazon_Sample_Metadata_2023
name: products2query
split: test
model_paths: 
- checkpoint-99855
- BeIR/query-gen-msmarco-t5-base-v1
sample: 500

