data:
  dataset_path: smartcat/Amazon-2023-GenQ
  dataset_subset: ''
  input_text_column: [title, description]
  label_text_column: short_query
  max_input_length: 512
  max_target_length: 30
  cache_dir: ./cache
  dev: false
train:
  output_dir_name: finetuned-amazon-product2query
  model_checkpoint: BeIR/query-gen-msmarco-t5-base-v1
  metrics: rouge
  batch_size: 32
  num_train_epochs: 8
  evaluation_strategy: epoch
  save_strategy: epoch
  learning_rate: 5.6e-05
  weight_decay: 0.01
  save_total_limit: 3
  predict_with_generate: true
  push_to_hub: false
  load_best_model_at_end: true
  metric_for_best_model: eval_rougeL
  greater_is_better: true
  logging_strategy: epoch
  report_to: none
